# Generated by Django 5.0.3 on 2026-05-08 16:00

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_supplier_follow_supplier_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CreditCVV',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CreditCardMonth',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CreditCardNO',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CreditCardType',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='CreditCardYear',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='CreditCVV',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='CreditCardMonth',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='CreditCardNO',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='CreditCardType',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='CreditCardYear',
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower_content_type',
            field=models.ForeignKey(default=accounts.models.get_default_customer_content_type, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{13,16}$', 'Enter a valid card number (13-16 digits).')])),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], default='visa', max_length=20)),
                ('expiry_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expiry_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2099)])),
                ('cvv', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', 'Enter a valid CVV (3 or 4 digits).')])),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Card',
                'verbose_name_plural': 'Payment Cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
