# Generated by Django 5.1.15 on 2026-05-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_loginhistory_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='performance_tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=20),
        ),
    ]
