# Generated by Django 5.0.3 on 2026-05-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_follow_follow_follower_idx_and_more'),
        ('course', '0008_enrollment_unique_enrollment'),
        ('products', '0014_collectionitem_unique_collection_item'),
        ('reviews', '0005_alter_review_ease_of_place_order_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('customer', 'product'), name='unique_product_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('customer', 'course'), name='unique_course_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('customer', 'supplier'), name='unique_supplier_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('delivery__isnull', False)), fields=('customer', 'delivery'), name='unique_delivery_review'),
        ),
    ]
