# Generated by Django 5.0.3 on 2026-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customer_creditcvv_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower_content_type', 'follower_object_id'], name='follow_follower_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['supplier'], name='follow_supplier_idx'),
        ),
    ]
