# Generated by Django 5.2.14 on 2026-05-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_follow_follow_follower_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_approve_withdrawals', 'Can approve withdrawals'), ('can_refund_orders', 'Can refund orders'), ('can_suspend_users', 'Can suspend users'), ('can_verify_suppliers', 'Can verify suppliers'), ('can_manage_courses', 'Can manage courses'), ('can_manage_products', 'Can manage products'), ('can_manage_disputes', 'Can manage disputes'), ('can_view_financial_reports', 'Can view financial reports'), ('can_view_audit_logs', 'Can view audit logs'), ('can_manage_support_tickets', 'Can manage support tickets')]},
        ),
    ]
