[pytest]
DJANGO_SETTINGS_MODULE = Handcrafts.settings
python_files = tests.py test_*.py *_tests.py
addopts = -v --reuse-db

markers =
    api: API integration tests
    rbac: role based access control tests
    payment: payment tests with mocked providers
    slow: slow tests
