# Generated by Django 5.0.3 on 2026-05-21 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursevideos_unique_lecture_per_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('Course', 'EnrolledUser'), name='unique_enrollment'),
        ),
    ]
