# Generated by Django 5.2.14 on 2026-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_enrollment_unique_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseTitle_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='CourseTitle_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='address_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursevideos',
            name='Description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideos',
            name='Description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideos',
            name='LectureTitle_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursevideos',
            name='LectureTitle_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
