# Generated by Django 5.0.3 on 2026-05-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_products_pr_product_971b37_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'product'), name='unique_collection_item'),
        ),
    ]
