# Generated by Django 5.2.14 on 2026-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_follow_follow_follower_idx_and_more'),
        ('products', '0014_collectionitem_unique_collection_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matcategory',
            name='Title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matcategory',
            name='Title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductDescription_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductDescription_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductName_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductName_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ProductName_en', 'ProductDescription_en'], name='products_pr_Product_59643a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ProductName_ar', 'ProductDescription_ar'], name='products_pr_Product_f6b281_idx'),
        ),
    ]
