# Generated by Django 5.2.14 on 2026-05-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_description_ar_category_description_en_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='prod_name_desc_idx',
            old_name='products_pr_Product_971b37_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='prod_price_idx',
            old_name='products_pr_UnitPri_618b96_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='prod_rating_idx',
            old_name='products_pr_Rating_5236fa_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='prod_name_desc_idx-en',
            old_name='products_pr_Product_59643a_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='prod_name_desc_idx-ar',
            old_name='products_pr_Product_f6b281_idx',
        ),
    ]
