# Generated by Django 4.2.30 on 2026-06-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_portal', '0002_changelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('outage', 'Outage')], default='healthy', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('schema_url', models.CharField(max_length=255)),
                ('endpoint_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
